[build]
  command = "yarn && yarn testbuild"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Content-Security-Policy = "default-src 'none';connect-src 'self' *.google-analytics.com;prefetch-src 'self'; manifest-src 'self'; style-src 'self' 'unsafe-inline'; base-uri 'none'; frame-src 'none'; frame-ancestors 'none'; form-action 'none'; script-src 'self' *.google-analytics.com 'unsafe-inline';img-src data: 'self' *.google-analytics.com;object-src 'none';"

[[headers]]
  for = "/*.*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "404.html"
  [headers.values]
    Cache-Control = "max-age=300"
